### ISSUE TITLE
com.semmle.util.exception.CatastrophicError: Program depends on template extensional selectedSourceFile, but no value was supplied for it  

### ISSUE THREAD

**Issue by dwisiswant0** [github/codeql-go#365]
Hi,

I can run a single rule without any problem by using Codeql CLI, but when I pass the `codeql-go` rule folder, I get the following error.

```
...
Starting evaluation of codeql-go/RedundantCode/SelfAssignment.ql.
Starting evaluation of codeql-go/RedundantCode/RedundantRecover.ql.
Starting evaluation of codeql-go/localReferences.ql.
Starting evaluation of codeql-go/AlertSuppression.ql.
Starting evaluation of codeql-go/Metrics/FLinesOfCode.ql.
Starting evaluation of codeql-go/Metrics/FLinesOfComment.ql.
Starting evaluation of codeql-go/printAst.ql.
Oops! A fatal internal error occurred.
com.semmle.util.exception.CatastrophicError: Program depends on template extensional selectedSourceFile, but no value was supplied for it
        at com.semmle.inmemory.caching.TemplateStore.<init>(TemplateStore.java:34)
        at com.semmle.inmemory.MemoryBackend.executeQuery(MemoryBackend.java:324)
        at com.semmle.cli2.ql.EvaluationCommon.lambda$executeQueryAsync$2(EvaluationCommon.java:181)
        at com.semmle.util.concurrent.FutureUtils.futureAutoclose(FutureUtils.java:185)
        at com.semmle.cli2.ql.EvaluationCommon.executeQueryAsync(EvaluationCommon.java:179)
        at com.semmle.cli2.execute.ExecuteQueriesCommand.lambda$executeSubcommand$3(ExecuteQueriesCommand.java:296)
        at com.semmle.cli2.ql.Paralleliser$1.lambda$next$0(Paralleliser.java:68)
        at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:217)
        at com.semmle.cli2.ql.Paralleliser.lambda$startMoreJobs$1(Paralleliser.java:98)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Could you please help me to solve the problem?

Thanks!

**Comment by smowton** [comment]
Could you please paste the full command you ran, and the output of `codeql version` and `codeql resolve languages`?

**Comment by max-schaefer** [comment]
The query `codeql-go/printAst.ql` cannot be run directly from the command line; it needs an extra input, which is normally provided by the Visual Studio Code extension, which runs this query to render AST previews.

In general, I would recommend running query suites like `go-alerts-lgtm` or `go-lgtm` rather than entire directories.
